### ISSUE TITLE
Issue in NotInExpression Class

### ISSUE THREAD

**Issue by jainaman26** [santanusinha/json-rules#27]
Please re validate below code, I think something is wrong with this code.. getting wrong result with the same.

@Override
    protected boolean evaluate(JsonNode evaluatedNode, Set<Object> values) {
        return (ComparisonUtils.isNodeMissingOrNull(evaluatedNode)
                || values.stream().allMatch(value -> ComparisonUtils.compare(evaluatedNode, value) != 0));
    }

**Comment by MISBMS** [comment]
There are quite a few test-cases validating the behaviour of the NOT_IN operator. A supporting test-case detailing the issue would be useful to debug further.
