### ISSUE TITLE
Integration with DB

### ISSUE THREAD

**Issue by adityaatul** [santanusinha/json-rules#34]
Can we integrate this codebase with a DB and instead of local data, can we use it on top of a DB (say mongo DB collection), and still apply the rules on the data loaded from DB? 
If yes, how to proceed with this, can you guide?

**Comment by santanusinha** [comment]
This works on json nodes .. it's is the responsibility of the calling system to form and create the json node. Are you talking bout using this to build a common query layer on multiple data sources instead of the in-memory one?

**Comment by adityaatul** [comment]
Thanks for the quick response.
Yes, kind of that. But in my case, the rules are very dynamic and the data set exist in Mongo DB. Do you think using a rule engine is an optimum way here?

**Comment by santanusinha** [comment]
MongoDB filtration or any DB filtration is done better on the DB layer and not at app layer. Closing this for now.
