### ISSUE TITLE
Add benchmarking or performance tests

### ISSUE THREAD

**Issue by swayamraina** [santanusinha/json-rules#35]
Add JMH benchmarking tests to check the performance.
Also, add this to README.md

**Comment by swayamraina** [comment]
@santanusinha, I wanted to add some JMH tests to the repo.

**Comment by santanusinha** [comment]
I can review and merge if you're willing to take this up.

**Comment by santanusinha** [comment]
BTW you might also want to take a look at [Hope](https://github.com/santanusinha/hope)

**Comment by swayamraina** [comment]
does this mean that this project is archived and new development is now being done in Hope?

**Comment by santanusinha** [comment]
No not at all..  This is extensively used in PhonePe.. No chance of this
getting deprecated...

**Comment by santanusinha** [comment]
No movement. Closing this.
