### ISSUE TITLE
JsonPath Expression

### ISSUE THREAD

**Issue by contatolucascosta** [santanusinha/json-rules#37]
Hi,

Is that possible use a _expression_ of JsonPath on definitions of rules ?

**Json input example:**
{ 
	"products":[
		{
			"id":1,
			"cost":{
				"value":100
			}
		},
		{
			"id":2,
			"cost":{
				"value":200
			}
		}
	]
}

**Json rule example:**
{
	"type": "less_than",
	"value": 1000,
	"path": "$.products[?(@.id == 2)].cost.value"
}

In this case, I expected to get **true**.
Is there a way to use jsonpath Expression "[?@.]" ?

**Comment by MISBMS** [comment]
The predicate less_than expects a singular numerical value on the lhs; but the path used above is an "indefinite" path that gives a list of matching values. You can check more about definite and indefinite paths [here](https://github.com/json-path/JsonPath).

As for an alternative way of achieving the same, you could instead go for contains_any predicate. Below is an example :
{
	"type": "contains_any",
	"path": "$.products.[?(@.id == 2 && @.cost.value < 1000)].id",
	"defaultResult": false,
	"values": [
		2
	],
	"extractValues": false
}

**Comment by contatolucascosta** [comment]
Hi.

I've got it.
Thank you!

cheers
