### ISSUE TITLE
Return unmatched keys when expression evaluation result is false

### ISSUE THREAD

**Issue by wapkch** [santanusinha/json-rules#39]
## Rule:
```
{
  "type" : "equals",
  "path" : "$.price",
  "value" : "100"
}
```

## Fact
```
{
"price": "1"
}
```

## Evaluation
When i do evaluation using json rules, the result is like this:
```
boolean result = expression.evaluate(fact);
```

## Quesion
Is there possible that the evaluation result include error keys info like this:
```
{
"result": false,
"error_info":
    {
        "key":"price",
        "provided": 1,
        "expected": 100
    }
}
``` 
This error info is really helpful in business scene.

**Comment by MISBMS** [comment]
This is undoubtably useful, but the exact nature of the expected details would depend on the business use-case. In fact we use it very extensively to convey the "why" / "how" part of it, if the rule evaluation fails.

I see a default implementation with option to override would be a very useful feature here. Let me get back on this.

**Comment by wapkch** [comment]
Thank you very much for your reply! 

I understand the expected details depend on the user-set rules, a default implementation with option to extend would be amazing. In the default implementation, returned details include the user-set rule of the unmatched key would be really useful too, if the rule evaluation fails. 

At present we used `json-rules` in permission system for user data authority calculation. It works really good in logic! But a more detailed error message must be displayed. I have to make a plan on the date. 

So I am very bold to ask if this feature is in the planning? About when is it likely to be available. Thank you again!

**Comment by wapkch** [comment]
> This is undoubtably useful, but the exact nature of the expected details would depend on the business use-case. In fact we use it very extensively to convey the "why" / "how" part of it, if the rule evaluation fails.
> 
> I see a default implementation with option to override would be a very useful feature here. Let me get back on this.

Thank you very much for your reply! 

I understand the expected details depend on the user-set rules, a default implementation with option to extend would be amazing. In the default implementation, returned details include the user-set rule of the unmatched key would be really useful too, if the rule evaluation fails. 

At present we used `json-rules` in permission system for user data authority calculation. It works really good in logic! But a more detailed error message must be displayed. I have to make a plan on the date. 

So I am very bold to ask if this feature is in the planning? About when is it likely to be available. Thank you again!

**Comment by MISBMS** [comment]
You can watch out for this [here](https://github.com/santanusinha/json-rules/pull/40)

**Comment by santanusinha** [comment]
This is merged now and new feature released. Closing this issue.
